language: generic
sudo: false
cache: apt

matrix:
  include:
    - env: CXX=g++-5 CC=gcc-5 INFOWARE_USE_X11=ON
      addons:
        apt:
          packages:
            - g++-5
            - libx11-dev
            - libxrandr-dev
          sources: &sources
            - r-packages-trusty
            - llvm-toolchain-trusty
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
            - llvm-toolchain-trusty-4.0
            - llvm-toolchain-trusty-5.0
    - env: CXX=g++-6 CC=gcc-6 INFOWARE_USE_X11=ON
      addons:
        apt:
          packages:
            - g++-6
            - libx11-dev
            - libxrandr-dev
          sources: *sources
    - env: CXX="clang++-3.8 -stdlib=libc++" CC=clang-3.8 INFOWARE_USE_X11=ON
      addons:
        apt:
          packages:
            - clang-3.8
            - libc++-dev
            - libx11-dev
            - libxrandr-dev
          sources: *sources
    - env: CXX="clang++-3.9 -stdlib=libc++" CC=clang-3.9 INFOWARE_USE_X11=ON
      addons:
        apt:
          packages:
            - clang-3.9
            - libc++-dev
            - libx11-dev
            - libxrandr-dev
          sources: *sources
    - env: CXX="clang++-4.0 -stdlib=libc++" CC=clang-4.0 INFOWARE_USE_X11=ON
      addons:
        apt:
          packages:
            - clang-4.0
            - libc++-dev
            - libx11-dev
            - libxrandr-dev
          sources: *sources
    - env: CXX="clang++-5.0 -stdlib=libc++" CC=clang-5.0 INFOWARE_USE_X11=ON
      addons:
        apt:
          packages:
            - clang-5.0
            - libc++-dev
            - libx11-dev
            - libxrandr-dev
          sources: *sources
    - env: INFOWARE_USE_X11=OFF
      os: osx
      osx_image: xcode8.3
    - env: INFOWARE_USE_X11=OFF
      os: osx
      osx_image: xcode9.2
  allow_failures:
    - env: CXX="clang++-5.0 -stdlib=libc++" CC=clang-5.0 INFOWARE_USE_X11=ON

script:
  - mkdir build && cd build
  - cmake -DINFOWARE_EXAMPLES=ON -DINFOWARE_TESTS=ON -DINFOWARE_USE_X11=$INFOWARE_USE_X11 ..
  - cmake --build . -- VERBOSE=1
  - ctest -V
