version: "{build}"
skip_tags: false

image:
  - Visual Studio 2015
  - Visual Studio 2017
platform:
  - x86
  - x64

clone_folder: C:\infoware

build_script:
  - git submodule update --init --recursive
  - mkdir build && cd build
  - set VERBOSE=1
  - cmake -DINFOWARE_EXAMPLES=ON -DINFOWARE_TESTS=ON -DINFOWARE_USE_D3D=ON ..
  - cmake --build . --config Debug
  - cmake --build . --config Release

test_script:
  - ctest -V --build-config Debug
  - ctest -V --build-config Release

notifications:
  - provider: Email
    to:
      - nabijaczleweli@gmail.com
      - phdofthehouse@gmail.com
    on_build_status_changed: true
